site_name: 厦门大学·RoboMaster·项目管理
site_url: https://xmu-rm-project-management.readthedocs.io/en/master/
site_favicon: favicon.ico
nav:
- 团队信息:
    - 团队架构: TeamStructure.md
    - 团队章程: TeamCharter.md
    - 队员信息库: https://docs.qq.com/sheet/DR0VuR0xLRVppU2VT
    - 成果信息库: AchievementInformationBase.md
- 项目进展:
    - 时间规划: TimeSchedule.md
    - 进度记录: ProgressRecord.md
    - 进度分析: ScheduleAnalysis.md
    - 理论导入: TheoryIntroduction.md
- 成本预算:
    - 团队预算: TeamBudget.md
    - 支出流水: ExpenditureRecord.htm
    - 兵种BOM: ArmsBOM.md
    - 成本分析: CostAnalysis.md
- 团队事项:
    - 会议记录: MeetingMinutes.md
    - 团队建设: TeamBuilding.md
    - 团队文化: TeamCulture.md
    - 团队规范: TeamNorms.md
    
theme: readthedocs
site_author: ASR-Crash
copyright: Copyright © 2021 ASR-Crash
